### ISSUE TITLE
challenge-make-numpy-array-your-shape

### ISSUE THREAD

**Issue by GodsDusk** [labex-labs/scenarios#126]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Make Numpy Array Your Shape
- **Suggest Steps 建议步骤数**:4
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`numpy/reshape`**
- **`numpy/concatenate`**
- **`numpy/stack`**
- **`numpy/split`**

**Comment by GodsDusk** [comment]
# Make Numpy Array Your Shape

## Introduction

In this challenge, you will be presented with different sub-challenges that will require you to manipulate Numpy arrays to your desired shape. These sub-challenges will test your ability to reshape arrays, concatenate and stack arrays, and split arrays into multiple sub-arrays. By completing these sub-challenges, you will gain a deeper understanding of how to manipulate Numpy arrays and their dimensions.

## Sub-Challenge 1: Reshape an Array

### TODO

Write a function `reshape_array(arr: np.ndarray, new_shape: tuple) -> np.ndarray` that takes in an array `arr` and a new shape `new_shape`, and returns a new Numpy array with the same data but a new shape. If the new shape is not compatible with the number of elements in the original array, raise a ValueError.

For example:

```python
>>> arr = np.array([[1, 2, 3], [4, 5, 6]])
>>> reshape_array(arr, (3, 2))
array([[1, 2],
       [3, 4],
       [5, 6]])
       
>>> reshape_array(arr, (3, 3)) # Raises ValueError
```

## Sub-Challenge 2: Concatenate Arrays

### TODO

Write a function `concatenate_arrays(arr1: np.ndarray, arr2: np.ndarray, axis: int) -> np.ndarray` that takes in two Numpy arrays `arr1` and `arr2` and an axis along which to concatenate the arrays. The function should return a new Numpy array that is the concatenation of the two input arrays along the specified axis.

For example:

```python
>>> arr1 = np.array([[1, 2], [3, 4]])
>>> arr2 = np.array([[5, 6], [7, 8]])
>>> concatenate_arrays(arr1, arr2, axis=0)
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

>>> concatenate_arrays(arr1, arr2, axis=1)
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])
```

## Sub-Challenge 3: Stack Arrays

### TODO

Write a function `stack_arrays(arr1: np.ndarray, arr2: np.ndarray, axis: int) -> np.ndarray` that takes in two Numpy arrays `arr1` and `arr2` and an axis along which to stack the arrays. The function should return a new Numpy array that is the stacked version of the two input arrays along the specified axis.

For example:

```python
>>> arr1 = np.array([1, 2, 3])
>>> arr2 = np.array([4, 5, 6])
>>> stack_arrays(arr1, arr2, axis=0)
array([[1, 2, 3],
       [4, 5, 6]])

>>> stack_arrays(arr1, arr2, axis=1)
array([[1, 4],
       [2, 5],
       [3, 6]])
```

## Sub-Challenge 4: Split an Array

### TODO

Write a function `split_array(arr: np.ndarray, indices_or_sections: Union[int, List[int]], axis: Optional[int] = None) -> List[np.ndarray]` that takes in a Numpy array `arr`, an integer `indices_or_sections`, and an optional axis `axis`. The function should return a list of Numpy arrays that are the splits of the input array along the specified axis. If the input integer `indices_or_sections` is a scalar, the input array will be split into equally sized chunks along the specified axis. If `indices_or_sections` is a list of integers, the input array will be split into the specified sections along the specified axis.

For example:

```python
>>> arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
>>> split_array(arr, 3, axis=0)
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

>>> split_array(arr, 2, axis=1)
[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

>>> split_array(arr, [1, 2], axis=0)
[array([[1, 2, 3]]), array([[4, 5, 6], [7, 8, 9]])]
```

## Conclusion

In this challenge, you used Numpy to perform various array operations such as reshape, concatenate, stack, and split. By completing these sub-challenges, you should have gained a deeper understanding of how to manipulate Numpy arrays and their dimensions. Keep practicing and exploring Numpy to become an expert in scientific computing with Python!

**Comment by GodsDusk** [comment]
# Solution

```python
import numpy as np
from typing import List, Union, Optional

def reshape_array(arr: np.ndarray, new_shape: tuple) -> np.ndarray:
    """
    Reshape an array to a new shape.

    Parameters:
        arr (np.ndarray): Input array to be reshaped
        new_shape (tuple): Desired shape of the array

    Returns:
        np.ndarray: Reshaped array

    Raises:
        ValueError: If the new shape is not compatible with the number of elements in the original array
    """
    if np.prod(arr.shape) != np.prod(new_shape):
        raise ValueError("New shape is not compatible with number of elements in input array")
    return np.reshape(arr, new_shape)


def concatenate_arrays(arr1: np.ndarray, arr2: np.ndarray, axis: int) -> np.ndarray:
    """
    Concatenate two arrays along a specified axis.

    Parameters:
        arr1 (np.ndarray): First input array to be concatenated
        arr2 (np.ndarray): Second input array to be concatenated
        axis (int): Axis along which to concatenate the arrays

    Returns:
        np.ndarray: Concatenated array
    """
    return np.concatenate((arr1, arr2), axis=axis)


def stack_arrays(arr1: np.ndarray, arr2: np.ndarray, axis: int) -> np.ndarray:
    """
    Stack two arrays along a specified axis.

    Parameters:
        arr1 (np.ndarray): First input array to be stacked
        arr2 (np.ndarray): Second input array to be stacked
        axis (int): Axis along which to stack the arrays

    Returns:
        np.ndarray: Stacked array
    """
    return np.stack((arr1, arr2), axis=axis)


def split_array(arr: np.ndarray, indices_or_sections: Union[int, List[int]], axis: Optional[int] = None) -> List[np.ndarray]:
    """
    Split an array into multiple sub-arrays along a specified axis.

    Parameters:
        arr (np.ndarray): Input array to be split
        indices_or_sections (Union[int, List[int]]): If an integer, specifies the number of equally-sized sub-arrays
            to be created along the specified axis. If a list of integers, specifies the indices at which to split the array.
        axis (Optional[int]): Axis along which to split the array. Default is None, which means the array is flattened before splitting.

    Returns:
        List[np.ndarray]: List of sub-arrays created by splitting the input array

    Raises:
        ValueError: If the number of sections in the list is not compatible with the size of the array along the specified axis
    """
    return np.split(arr, indices_or_sections, axis=axis)
```

**Comment by GodsDusk** [comment]
```python
import unittest
import numpy as np
from numpy.testing import assert_array_equal
from numpy.testing import assert_raises
from numpy.testing import assert_allclose

class TestNumpyArrayOperations(unittest.TestCase):
    
    def test_reshape_array(self):
        # Test 1
        arr1 = np.array([[1, 2, 3], [4, 5, 6]])
        expected1 = np.array([[1, 2], [3, 4], [5, 6]])
        assert_array_equal(reshape_array(arr1, (3, 2)), expected1)
        
        # Test 2
        arr2 = np.array([[1, 2], [3, 4], [5, 6]])
        expected2 = np.array([1, 2, 3, 4, 5, 6])
        assert_array_equal(reshape_array(arr2, (6,)), expected2)
        
        # Test 3
        arr3 = np.array([[1, 2, 3], [4, 5, 6]])
        with self.assertRaises(ValueError):
            reshape_array(arr3, (2, 2))
        
    def test_concatenate_arrays(self):
        # Test 1
        arr1 = np.array([[1, 2], [3, 4]])
        arr2 = np.array([[5, 6], [7, 8]])
        expected1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
        assert_array_equal(concatenate_arrays(arr1, arr2, axis=0), expected1)
        
        # Test 2
        arr3 = np.array([[1, 2], [3, 4]])
        arr4 = np.array([[5, 6], [7, 8]])
        expected2 = np.array([[1, 2, 5, 6], [3, 4, 7, 8]])
        assert_array_equal(concatenate_arrays(arr3, arr4, axis=1), expected2)
    
    def test_stack_arrays(self):
        # Test 1
        arr1 = np.array([1, 2, 3])
        arr2 = np.array([4, 5, 6])
        expected1 = np.array([[1, 2, 3], [4, 5, 6]])
        assert_array_equal(stack_arrays(arr1, arr2, axis=0), expected1)
        
        # Test 2
        arr3 = np.array([1, 2, 3])
        arr4 = np.array([4, 5, 6])
        expected2 = np.array([[1, 4], [2, 5], [3, 6]])
        assert_array_equal(stack_arrays(arr3, arr4, axis=1), expected2)
        
    def test_split_array(self):
        # Test 1
        arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        expected1 = [np.array([[1, 2, 3]]), np.array([[4, 5, 6]]), np.array([[7, 8, 9]])]
        assert_array_equal(split_array(arr1, 3, axis=0), expected1)
        
        # Test 2
        arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
        expected2 = [np.array([[1, 2]]), np.array([[3, 4]]), np.array([[5, 6], [7, 8]])]
        assert_array_equal(split_array(arr2, 2, axis=0), expected2)
        
        # Test 3
        arr3 = np.array([[1, 2, 3], [4, 5, 6]])
        with self.assertRaises(ValueError):
            split_array(arr3, [1, 2], axis=0)
```

**Comment by cataeo** [comment]
认领，3.6

**Comment by cataeo** [comment]
选题，3.6

**Comment by cataeo** [comment]
章绮娟，3.6
