### ISSUE TITLE
challenge-make-object-like-dict

### ISSUE THREAD

**Issue by GodsDusk** [labex-labs/scenarios#171]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Make Object Like Dict
- **Suggest Steps 建议步骤数**:2
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/__getitem__`**
- **`python/__setitem__`**
- **`python/__delitem__`**
- **`python/__len__`**
- **`python/__contains__`**
- **`python/__iter__`**
- `python/dict`

**Comment by GodsDusk** [comment]
# Make Object Like Dict

In this programming challenge, you will create a Python class that behaves like a dictionary using magic methods. 

## Sub-Challenge Name: Basic Functionality

### Introduction

Your first task is to create a class that can be used like a dictionary with basic functionality. The class should store key-value pairs and allow them to be accessed, added, and removed using square bracket notation.

### TODO

Create a class called `DictLikeObject` that:

- Has an internal dictionary to store key-value pairs.
- Implements the `__getitem__` method to retrieve values using square bracket notation. If the key does not exist, raise a `KeyError`.
- Implements the `__setitem__` method to set values using square bracket notation.
- Implements the `__delitem__` method to remove key-value pairs using square bracket notation. If the key does not exist, raise a `KeyError`.
- Implements the `__len__` method to return the number of key-value pairs in the dictionary.

## Sub-Challenge Name: Advanced Functionality

### Introduction

Your next task is to implement additional magic methods to make your `DictLikeObject` even more powerful. You will implement the `__contains__`, `__iter__`, and `keys` methods to allow for membership testing, iteration, and getting a list of keys.

### TODO

- Implement the `__contains__` method to allow for membership testing using the `in` keyword.
- Implement the `__iter__` method to allow for iteration over keys using a for loop.
- Implement a method called `keys` that returns a list of keys in the dictionary.

## Conclusion

By implementing these magic methods, you have created a powerful and flexible object that can be used like a dictionary. You can now create instances of your `DictLikeObject` and use them in place of regular dictionaries in your Python programs.

**Comment by GodsDusk** [comment]
# Solution

## Sub-Challenge Name: Basic Functionality

```python
class DictLikeObject:
    """
    A class that behaves like a dictionary using magic methods.
    """

    def __init__(self):
        self._data = {}

    def __getitem__(self, key: str) -> Any:
        """
        Retrieve the value for a given key using square bracket notation.

        Args:
            key: The key to retrieve the value for.

        Returns:
            The value for the given key.

        Raises:
            KeyError: If the key does not exist in the dictionary.
        """
        return self._data[key]

    def __setitem__(self, key: str, value: Any) -> None:
        """
        Set the value for a given key using square bracket notation.

        Args:
            key: The key to set the value for.
            value: The value to set.

        Returns:
            None.
        """
        self._data[key] = value

    def __delitem__(self, key: str) -> None:
        """
        Remove the key-value pair for a given key using square bracket notation.

        Args:
            key: The key to remove.

        Returns:
            None.

        Raises:
            KeyError: If the key does not exist in the dictionary.
        """
        del self._data[key]

    def __len__(self) -> int:
        """
        Return the number of key-value pairs in the dictionary.

        Returns:
            The number of key-value pairs in the dictionary as an integer.
        """
        return len(self._data)
```

## Sub-Challenge Name: Advanced Functionality

```python
class DictLikeObject:
    """
    A class that behaves like a dictionary using magic methods.
    """

    def __init__(self):
        self._data = {}

    def __getitem__(self, key: str) -> Any:
        """
        Retrieve the value for a given key using square bracket notation.

        Args:
            key: The key to retrieve the value for.

        Returns:
            The value for the given key.

        Raises:
            KeyError: If the key does not exist in the dictionary.
        """
        return self._data[key]

    def __setitem__(self, key: str, value: Any) -> None:
        """
        Set the value for a given key using square bracket notation.

        Args:
            key: The key to set the value for.
            value: The value to set.

        Returns:
            None.
        """
        self._data[key] = value

    def __delitem__(self, key: str) -> None:
        """
        Remove the key-value pair for a given key using square bracket notation.

        Args:
            key: The key to remove.

        Returns:
            None.

        Raises:
            KeyError: If the key does not exist in the dictionary.
        """
        del self._data[key]

    def __len__(self) -> int:
        """
        Return the number of key-value pairs in the dictionary.

        Returns:
            The number of key-value pairs in the dictionary as an integer.
        """
        return len(self._data)

    def __contains__(self, key: str) -> bool:
        """
        Check if a key exists in the dictionary.

        Args:
            key: The key to check.

        Returns:
            True if the key exists in the dictionary, False otherwise.
        """
        return key in self._data

    def __iter__(self) -> Iterator:
        """
        Allow for iteration over keys in the dictionary using a for loop.

        Returns:
            An iterator over keys in the dictionary.
        """
        return iter(self._data)

    def keys(self) -> List[str]:
        """
        Return a list of keys in the dictionary.

        Returns:
            A list of keys in the dictionary.
        """
        return list(self._data.keys())
```

**Comment by GodsDusk** [comment]
# Test

```python
import unittest
from typing import Any, List
from object_like_dict import DictLikeObject


class TestDictLikeObject(unittest.TestCase):
    def test_basic_functionality(self):
        # Test initialization
        d = DictLikeObject()
        self.assertEqual(len(d), 0)

        # Test setting and getting values
        d['key1'] = 'value1'
        self.assertEqual(d['key1'], 'value1')

        # Test removing key-value pairs
        del d['key1']
        self.assertNotIn('key1', d)

        # Test raising KeyError when getting, setting, and deleting nonexistent keys
        with self.assertRaises(KeyError):
            d['key1']
        with self.assertRaises(KeyError):
            del d['key1']
        with self.assertRaises(KeyError):
            d['key1'] = 'value1'

    def test_advanced_functionality(self):
        # Test membership testing
        d = DictLikeObject()
        d['key1'] = 'value1'
        self.assertIn('key1', d)
        self.assertNotIn('key2', d)

        # Test iteration over keys
        d['key2'] = 'value2'
        keys = []
        for key in d:
            keys.append(key)
        self.assertEqual(keys, ['key1', 'key2'])

        # Test getting a list of keys
        self.assertEqual(d.keys(), ['key1', 'key2'])


if __name__ == '__main__':
    unittest.main()
```

**Comment by huhuhang** [comment]
认领超时，重新开放。

**Comment by GodsDusk** [comment]
> 认领超时，重新开放。

没关联上 https://github.com/labex-labs/scenarios/pull/221
