### ISSUE TITLE
challenge-command-line-calculator

### ISSUE THREAD

**Issue by huhuhang** [labex-labs/scenarios#21]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first.**
> **请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Command Line Calculator
- **Suggest Steps 建议步骤数**: 1
- **Suggest Image 建议环境**: `webide-ubuntu:2004`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/argparse`**
- `python/if_else`

**Comment by huhuhang** [comment]
#### You:
Generate a programming challenge of Python argparse Module, using markdown.

#### ChatGPT:
# Python argparse Challenge

The `argparse` module in Python is a powerful tool for parsing command-line arguments. In this challenge, you will write a program that uses the `argparse` module to parse command-line arguments and perform some simple arithmetic operations based on the arguments.

## Requirements

1. Your program should accept the following command-line arguments:-a or --add: Add two numbers. The two numbers should be specified as separate arguments after the -a or --add option.-s or --subtract: Subtract two numbers. The two numbers should be specified as separate arguments after the -s or --subtract option.-m or --multiply: Multiply two numbers. The two numbers should be specified as separate arguments after the -m or --multiply option.-d or --divide: Divide two numbers. The two numbers should be specified as separate arguments after the -d or --divide option.For example, if the user runs python my_program.py -a 1 2, the program should add the numbers 1 and 2.
2. Your program should display an error message if the user provides an invalid option or an insufficient number of arguments.
3. Your program should handle errors gracefully and display a meaningful error message if the user provides non-numeric arguments.

## Evaluation

Your solution will be evaluated on the following criteria:

1. Correctness of the arithmetic operations
2. Proper handling of invalid options and arguments
3. User-friendly error messages
4. Code readability and maintainability

## Bonus

- Implement additional arithmetic operations (e.g. exponentiation)
- Support for floating-point numbers

Good luck!

#### You:
Generate the answer for this challenge, the answer should contain docstring and type hint.

#### ChatGPT:
Here is a sample solution to the `argparse` challenge in Python:

```python
import argparse

def add(a: int, b: int) -> int:
    """Return the sum of two numbers."""
    return a + b

def subtract(a: int, b: int) -> int:
    """Return the difference of two numbers."""
    return a - b

def multiply(a: int, b: int) -> int:
    """Return the product of two numbers."""
    return a * b

def divide(a: int, b: int) -> float:
    """Return the quotient of two numbers."""
    return a / b

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Perform arithmetic operations on two numbers.')
    group = parser.add_mutually_exclusive_group()
    group.add_argument('-a', '--add', nargs=2, type=int, metavar=('NUM1', 'NUM2'), help='add NUM1 and NUM2')
    group.add_argument('-s', '--subtract', nargs=2, type=int, metavar=('NUM1', 'NUM2'), help='subtract NUM2 from NUM1')
    group.add_argument('-m', '--multiply', nargs=2, type=int, metavar=('NUM1', 'NUM2'), help='multiply NUM1 and NUM2')
    group.add_argument('-d', '--divide', nargs=2, type=int, metavar=('NUM1', 'NUM2'), help='divide NUM1 by NUM2')
    args = parser.parse_args()

    if args.add:
        result = add(*args.add)
        print(f"{args.add[0]} + {args.add[1]} = {result}")
    elif args.subtract:
        result = subtract(*args.subtract)
        print(f"{args.subtract[0]} - {args.subtract[1]} = {result}")
    elif args.multiply:
        result = multiply(*args.multiply)
        print(f"{args.multiply[0]} * {args.multiply[1]} = {result}")
    elif args.divide:
        result = divide(*args.divide)
        print(f"{args.divide[0]} / {args.divide[1]} = {result}")
    else:
        parser.print_help()
```

This solution uses the `argparse` module to define the command-line arguments and parse them. It also defines four functions for the four arithmetic operations, each with a docstring and type hint. In the `if __name__ == '__main__'` block, the solution uses the `argparse` module to parse the command-line arguments and perform the appropriate operation based on the arguments provided by the user. Finally, the result of the operation is printed to the console.

#### You:
Generate test code for this challenge

#### ChatGPT:
Here's some sample test code for the solution to the `argparse` challenge:

```python
import subprocess
import sys

def test_addition():
    result = subprocess.run(['python', 'my_program.py', '-a', '1', '2'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '1 + 2 = 3'

    result = subprocess.run(['python', 'my_program.py', '--add', '10', '20'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '10 + 20 = 30'

def test_subtraction():
    result = subprocess.run(['python', 'my_program.py', '-s', '10', '5'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '10 - 5 = 5'

    result = subprocess.run(['python', 'my_program.py', '--subtract', '20', '10'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '20 - 10 = 10'

def test_multiplication():
    result = subprocess.run(['python', 'my_program.py', '-m', '10', '5'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '10 * 5 = 50'

    result = subprocess.run(['python', 'my_program.py', '--multiply', '20', '10'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '20 * 10 = 200'

def test_division():
    result = subprocess.run(['python', 'my_program.py', '-d', '10', '5'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '10 / 5 = 2.0'

    result = subprocess.run(['python', 'my_program.py', '--divide', '20', '10'], stdout=subprocess.PIPE)
    assert result.stdout.decode().strip() == '20 / 10 = 2.0'

def test_invalid_option():
    result = subprocess.run(['python', 'my_program.py', '--invalid'], stderr=subprocess.PIPE)
    assert 'unrecognized arguments: --invalid' in result.stderr.decode().strip()

def test_insufficient_arguments():
    result = subprocess.run(['python', 'my_program.py', '-a'], stderr=subprocess.PIPE)
    assert 'the following arguments are required: NUM1, NUM2' in result.stderr.decode().strip()

if __name__ == '__main__':
    test_addition()
    test_subtraction()
    test_multiplication()
    test_division()
    test_invalid_option()
    test_insufficient_arguments()
    print('All
```

#### You:
Generate test code using shell

#### ChatGPT:
Here's some sample test code using shell for the solution to the `argparse` challenge:

```bash
#!/bin/bash

# Test addition
result=$(python my_program.py -a 1 2)
if [ "$result" == "1 + 2 = 3" ]; then
  echo "Test addition: PASS"
else
  echo "Test addition: FAIL"
fi

# Test subtraction
result=$(python my_program.py -s 10 5)
if [ "$result" == "10 - 5 = 5" ]; then
  echo "Test subtraction: PASS"
else
  echo "Test subtraction: FAIL"
fi

# Test multiplication
result=$(python my_program.py -m 10 5)
if [ "$result" == "10 * 5 = 50" ]; then
  echo "Test multiplication: PASS"
else
  echo "Test multiplication: FAIL"
fi

# Test division
result=$(python my_program.py -d 10 5)
if [ "$result" == "10 / 5 = 2.0" ]; then
  echo "Test division: PASS"
else
  echo "Test division: FAIL"
fi

# Test invalid option
result=$(python my_program.py --invalid 2>&1)
if [ "$result" == "unrecognized arguments: --invalid" ]; then
  echo "Test invalid option: PASS"
else
  echo "Test invalid option: FAIL"
fi

# Test insufficient arguments
result=$(python my_program.py -a 2>&1)
if [ "$result" == "the following arguments are required: NUM1, NUM2" ]; then
  echo "Test insufficient arguments: PASS"
else
  echo "Test insufficient arguments: FAIL"
fi
```

This test code uses the shell to run the solution to the `argparse` challenge and test the different operations and error handling cases. The results of each test are printed to the console, indicating whether the test passed or failed.

**Comment by huhuhang** [comment]
建议直接将上述内容，重组为一个 challenge。其中需要根据参考答案，给用户预留不完整的基础代码文件。参考 master 分支下已经完成的 challenge。

`my_program.py` 文件名，建议改为更正式的 `calculator.py`

**Comment by Asaakii** [comment]
李鸿 02.19
