### ISSUE TITLE
challenge-file-permission

### ISSUE THREAD

**Issue by mercury7720** [labex-labs/scenarios#23]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first.**
> **请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  File Permission
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `webide-ubuntu:2004`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- `linux/chown`
- `linux/chmod`
- `linux/touch`
- `linux/ls`

**Comment by JasonSorria** [comment]
2023-02-18
