### ISSUE TITLE
challenge-mastering-text-manipulation

### ISSUE THREAD

**Issue by xinxin68** [labex-labs/scenarios#265]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Mastering Text Manipulation
- **Suggest Steps 建议步骤数**:3
- **Suggest Image 建议环境**: `vnc-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`linux/grep`**
- **`linux/sed`**
- **`linux/awk`**
- `linux/touch`
- `Linux/redirect`

**Comment by GuoJiang-yw** [comment]
3.15 郭江

**Comment by xinxin68** [comment]
每个步骤所对应的检测脚本如下：
Step 1:

```
echo -e "This is line 1.\nThis is line 2.\nThis is line 3\n" > test_output.txt
if grep "line" example.txt | cmp -s - test_output.txt; then
    echo "Output is correct"
else
    echo "Output is incorrect"
fi
rm -rf  test_output.txt
```

Step 2:

```
echo -e "John Smith\nJane Doe\nBob Johnson\n" > test_output.txt
if awk -F ',' '{print $1}' example.txt | cmp -s - test_output.txt; then
    echo "Output is correct"
else
    echo "Output is incorrect"
fi
rm -rf test_output.txt

```

Step 3:

```
echo -e "This is string 1.\nThis is string 2.\nThis is string 3\n" > test_output.txt
if sed 's/line/string/g' example.txt | cmp -s - test_output.txt; then
    echo "Output is correct"
else
    echo "Output is incorrect"
fi
```

**Comment by huhuhang** [comment]
认领超时，重新开放。
