### ISSUE TITLE
lab-docker-lifecycle-management

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#335]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Docker Lifecycle Management
- **Suggest Steps 建议步骤数**:4
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`docker/run`**
- **`docker/ps`**
- **`docker/stop`**
- **`docker/rm`**
- **`docker/rmi`**
- `docker/build`

**Comment by joker-bai** [comment]
# Docker Lifecycle Management

## Introduction
Docker is a platform that enables developers to package, distribute, and run applications inside containers. Containerization is a great way to simplify application deployment and increase flexibility. In this lab, we will go through the basics of Docker lifecycle management, including creating, running, stopping, and removing containers.


## Step 1: Create a Docker Image
In this step, we will create a simple Docker image that contains a web server. 

1. Create a new directory and navigate into it.
2. Create a file named `Dockerfile` with the following content:

```
FROM nginx:latest
COPY index.html /usr/share/nginx/html/
```

This Dockerfile uses the latest version of the nginx image as the base image and copies an `index.html` file into the `/usr/share/nginx/html/` directory inside the container.

3. Create an `index.html` file with the following content:

```
<!DOCTYPE html>
<html>
<head>
    <title>Hello Docker!</title>
</head>
<body>
    <h1>Hello Docker!</h1>
</body>
</html>
```

4. Build the Docker image by running the following command:

```
docker build -t my-web-server .
```

This command builds a new Docker image with the tag `my-web-server` using the Dockerfile in the current directory. The `.` at the end of the command indicates that the build context is the current directory.

## Step 2: Run a Docker Container
In this step, we will run a Docker container based on the image we created in the previous step.

1. Run the following command to start a new container based on the `my-web-server` image:

```
docker run -d -p 8080:80 my-web-server
```

This command starts a new container in detached mode (`-d`) with port forwarding from the host port 8080 to the container port 80 (`-p 8080:80`). The container runs the `my-web-server` image we created in the previous step.

2. Open a web browser and go to `http://localhost:8080` to see the web page served by the container.

## Step 3: Manage Docker Containers
In this step, we will learn how to manage Docker containers.

1. Run the following command to see the list of running Docker containers:

```
docker ps
```

This command lists all the running Docker containers along with their status, container ID, image, and other information.

2. Run the following command to stop the container we started in the previous step:

```
docker stop <CONTAINER_ID>
```

Replace `<CONTAINER_ID>` with the ID of the container you want to stop. You can get the container ID from the output of the `docker ps` command.

3. Run the following command to remove the container:

```
docker rm <CONTAINER_ID>
```

Replace `<CONTAINER_ID>` with the ID of the container you want to remove.

## Step 4: Clean up
In this step, we will clean up the resources we created in the previous steps.

1. Run the following command to stop and remove all running containers:

```
docker container stop $(docker container ls -aq)
docker container rm $(docker container ls -aq)
```

This command stops and removes all running containers.

2. Run the following command to remove the `my-web-server` image:

```
docker rmi my-web-server
```

This command removes the Docker image with the tag `my-web-server`.

## Summary
In this lab, we learned the basics of Docker lifecycle management. We created a Docker image, ran a Docker container, and learned how to manage Docker containers. We also cleaned up the resources we created. Docker is a powerful tool that can simplify application deployment and increase flexibility. With Docker, you can easily package, distribute, and run applications inside containers.

**Comment by zhangdongdong7** [comment]
2023-04-11,zhangdongdong7
