### ISSUE TITLE
lab-accessing-and-managing-docker-container

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#336]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Accessing And Managing Docker Container
- **Suggest Steps 建议步骤数**: 4
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`docker/run`**
- **`docker/logs`**
- **`docker/stop`**
- **`docker/exec`**
- **`docker/rm`**
- **`docker/ps`**

**Comment by joker-bai** [comment]
# Accessing And Managing Docker Container
## Introduction
Docker is a powerful tool for deploying applications in containers, which are lightweight and portable environments that can run on any system with Docker installed. In this lab, we will learn how to access and manage Docker containers using the Docker command line interface (CLI). We will cover basic container management tasks, including starting and stopping containers, accessing container logs, and executing commands inside a container. 

## Step 1: Starting a Container
In this step, we will start a container and access its logs.

1. Run the following command to start a new container:

```
docker run -d --name my-container nginx
```

This command starts a new container based on the `nginx` image and gives it a name of `my-container`.

2. Run the following command to access the logs of the container:

```
docker logs my-container
```

This command prints the logs of the container to the terminal.

## Step 2: Stopping a Container
In this step, we will stop a running container.

1. Run the following command to stop the container we started in the previous step:

```
docker stop my-container
```

This command stops the running container with the name `my-container`.

2. Run the following command to confirm that the container has been stopped:

```
docker ps -a
```

This command lists all containers, including stopped containers. You should see the `my-container` container in the list with a status of `Exited`.

## Step 3: Executing Commands in a Container
In this step, we will execute a command inside a running container.

1. Run the following command to start a new container with a shell:

```
docker run -it --name my-shell-container ubuntu /bin/bash
```

This command starts a new container based on the `ubuntu` image and gives it a name of `my-shell-container`. The `/bin/bash` command starts a shell inside the container.

2. Run the following command to execute a command inside the running container:

```
docker exec my-shell-container echo "Hello World"
```

This command executes the `echo "Hello World"` command inside the `my-shell-container` container.

## Step 4: Removing a Container
In this step, we will remove a container.

1. Run the following command to remove the container we started in the previous step:

```
docker rm my-shell-container
```

This command removes the container with the name `my-shell-container`.

2. Run the following command to confirm that the container has been removed:

```
docker ps -a
```

This command lists all containers, including stopped containers. You should not see the `my-shell-container` container in the list.

## Conclusion
In this lab, we learned how to access and manage Docker containers using the Docker CLI. We covered basic container management tasks, including starting and stopping containers, accessing container logs, executing commands inside a container, and removing containers. With these skills, you can start exploring more complex Docker container management scenarios and get hands-on experience with Docker.

**Comment by xiachengfan** [comment]
xiachengfan,预计4月计13日前交付
