### ISSUE TITLE
lab-docker-multi-stage-build

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#343]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Docker Multi-stage Build
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`docker/build`**
- `docker/images`
- `docker/run`

**Comment by joker-bai** [comment]
# Docker Multi-stage Build

## Introduction

Docker Multi-stage Build is a feature that allows you to use multiple stages in a Dockerfile to create a final Docker image. In this lab, you will learn how to use Docker Multi-stage Build to create a smaller and more efficient Docker image.

## Prerequisites

Before starting this lab, you should have:

- A basic understanding of Docker and containerization.
- Docker installed on your computer.
- A terminal or command prompt open.

## Step 1: Create a Dockerfile with Multi-stage Build

The first step in using Docker Multi-stage Build is to create a Dockerfile with multiple stages. To do this, follow these steps:

1. Create a new directory called `myapp` and navigate into it:

```bash
mkdir myapp
cd myapp
```

2. Download NodeJS source code

```bash
git clone https://github.com/joker-bai/nodejs-example.git .
```

3. Create a new file called `Dockerfile` in the `myapp` directory:

```bash
touch Dockerfile
```

4. Open the `Dockerfile` file in a text editor, and add the following content:

```Dockerfile
# Stage 1: Build the application
FROM node:14-alpine AS base
WORKDIR /app
COPY . ./
RUN npm install

# Stage 2: Create the final image
FROM node:14-alpine
WORKDIR /app
COPY --from=base /app/ .
EXPOSE 3000
CMD [ "npm", "start" ]
```

This Dockerfile uses two stages. The first stage builds the application by installing the required dependencies and running the build script, and the second stage creates the final image by copying the compiled code from the first stage, installing only the production dependencies, and exposing the necessary port.

## Step 2: Build a Docker Image

The next step is to use the Dockerfile to build a Docker image. To do this, follow these steps:

1. Run the following command to build the Docker image:

```bash
docker build -t myapp .
```

This command builds a Docker image called `myapp` using the Dockerfile in the current directory (`.`).

2. Run the following command to list all Docker images:

```bash
docker images
```

This command lists all Docker images on your host, including the `myapp` image you just built.

## Step 3: Run a Docker Container

The final step is to use the Docker image to run a Docker container. To do this, follow these steps:

1. Run the following command to start a new Docker container:

```bash
docker run -p 3000:3000 myapp
```

This command starts a new Docker container using the `myapp` image you just built, and maps port 3000 on the container to port 3000 on the host.

2. Open a web browser and navigate to `http://localhost:3000` to access the running application.

## Summary

In this lab, you learned how to use Docker Multi-stage Build to create a smaller and more efficient Docker image. By using multiple stages in a Dockerfile, you can separate the build and runtime environments, and reduce the size of the final Docker image. With this knowledge, you can now start building your own Docker images using Multi-stage Build.

**Comment by zhangdongdong7** [comment]
vnc-ubuntu:2204这个环境没有docker
