### ISSUE TITLE
lab-examine-nodes-with-kubectl

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#351]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  Examine Nodes with Kubectl
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/get`**
- `kubernetes/describe`
- `kubernetes/label`
- `kubernetes/cordon`
- `kubernetes/uncordon`

**Comment by joker-bai** [comment]
# Examining Nodes with Kubectl

In this lab, you will learn how to use `kubectl` to examine the nodes in your Kubernetes cluster. You will start with basic node information and work your way up to more advanced topics such as taints and tolerations. This lab assumes that you have a Kubernetes cluster already set up and have `kubectl` installed.


## Step 1: Basic Node Information

The first thing you will do is get basic information about the nodes in your cluster.

1. To view a list of nodes in your cluster, run the following command:

   ```
   kubectl get nodes
   ```

   This will display a list of all the nodes in your cluster along with their status.

2. To get more detailed information about a specific node, run the following command:

   ```
   kubectl describe node <node-name>
   ```

   Replace `<node-name>` with the name of the node you want to examine. This will give you detailed information about the node's status, capacity, and usage.

## Step 2: Labels and Annotations

Labels and annotations can be used to add metadata to nodes in your cluster. This metadata can be used to select nodes for specific tasks or to filter nodes based on certain criteria.

1. To view the labels and annotations for a specific node, run the following command:

   ```
   kubectl get node <node-name> --show-labels=true
   ```

   This will display the labels and annotations for the specified node.

2. To add a label to a node, run the following command:

   ```
   kubectl label node <node-name> <label-key>=<label-value>
   ```

   Replace `<node-name>` with the name of the node you want to label, `<label-key>` with the name of the label, and `<label-value>` with the value for the label.

3. To add an annotation to a node, run the following command:

   ```
   kubectl annotate node <node-name> <annotation-key>=<annotation-value>
   ```

   Replace `<node-name>` with the name of the node you want to annotate, `<annotation-key>` with the name of the annotation, and `<annotation-value>` with the value for the annotation.

## Step 3: Taints and Tolerations

Taints and tolerations can be used to control which pods can be scheduled on which nodes in your cluster. A taint is a special label that marks a node as unsuitable for certain types of pods, and a toleration is a setting that allows a pod to be scheduled on a node with a matching taint.

1. To view the taints for a specific node, run the following command:

   ```
   kubectl describe node <node-name> | grep Taints
   ```

   This will display the taints for the specified node.

2. To add a taint to a node, run the following command:

   ```
   kubectl taint node <node-name> <taint-key>=<taint-value>:<taint-effect>
   ```

   Replace `<node-name>` with the name of the node you want to taint, `<taint-key>` with the name of the taint, `<taint-value>` with the value for the taint, and `<taint-effect>` with the effect that the taint should have (`NoSchedule`, `PreferNoSchedule`, or `NoExecute`).

3. To add a toleration to a pod, add the following section to the pod's YAML file:

	```
	apiVersion: v1
	kind: Pod
	metadata:
	  name: my-pod
	spec:
	  containers:
	    - name: my-container
	      image: my-image
	  tolerations:
	    - key: <taint-key>
	      operator: Exists
	      effect: <taint-effect>
	```

  Replace `<taint-key>` with the name of the taint, and `<taint-effect>` with the effect that the taint should have (`NoSchedule`, `PreferNoSchedule`, or `NoExecute`).


## Step 3: Check Node Labels

Nodes can be labeled to help identify their purpose or characteristics. Use the following command to check the labels on the node:

```
kubectl get nodes --show-labels
```

This will output a list of all the nodes in the cluster along with their labels.

## Step 4: View Node Capacity and Resource Usage

To view the available resources on a node, use the following command:

```
kubectl describe node <node-name>
```

Replace `<node-name>` with the name of the node you want to examine.

This will provide detailed information about the node, including its capacity and current resource usage.

## Step 5: View Node Events

Node events can provide valuable insight into any issues or errors that may be affecting a node. To view the events for a specific node, use the following command:

```
kubectl describe node <node-name> | grep -i events
```

Replace `<node-name>` with the name of the node you want to examine.

This will output a list of all the events associated with the node.

## Step 6: Cordon and Uncordon a Node

In some cases, you may need to take a node out of rotation for maintenance or other reasons. Kubernetes provides a way to mark a node as unschedulable so that no new pods are scheduled on it. This is called "cordon".

To cordon a node, use the following command:

```shell
kubectl cordon <NODE_NAME>
```

Replace `<NODE_NAME>` with the name of the node you want to cordon.

Then Use the following command to check the node status:

```shell
kubectl get node
```

To uncordon a node and allow new pods to be scheduled on it, use the following command:

```shell
kubectl uncordon <NODE_NAME>
```

Replace `<NODE_NAME>` with the name of the node you want to uncordon.

Note that cordoning a node does not automatically move any existing pods off the node. You should manually delete or move the pods before cordoning the node to avoid any disruption.

Congratulations, you have learned how to cordon and uncordon a node in Kubernetes.

## Summary

In this lab, you learned how to examine nodes in a Kubernetes cluster using `kubectl`. You learned how to list nodes, check their status, view their labels, and inspect their capacity and resource usage. You also learned how to drain and uncordon nodes for maintenance and upgrades.

**Comment by joker-bai** [comment]
正文里的变量需要根据实际情况进行替换。

**Comment by huhuhang** [comment]
标题建议改成 Examine Nodes with Kubectl
