### ISSUE TITLE
challenge-get-local-time

### ISSUE THREAD

**Issue by Shuchong-LI** [labex-labs/scenarios#381]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Get Local Time
- **Suggest Steps 建议步骤数**:1
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- `python/datetime`
- `python/pytz`
- `python/requests`

**Comment by Shuchong-LI** [comment]
# Get Local Time

## Background

In today's globalized world, it is essential to be aware of the local time in different cities, especially when conducting business or traveling. In this coding challenge, you will be required to develop a program that can retrieve the local time of any city in the world, given its name.

## Introduction

The program you will create will take as input the name of a city in the world and return the local time in that city. To do this, your program will need to connect to an API that provides timezone information for cities around the world. You will then use the timezone information to calculate the local time in the given city.

## Examples

Suppose the user inputs "Paris" as the city. Your program should connect to the API, retrieve the timezone information for Paris, and calculate the local time in Paris. The output should look something like this:

```
The local time in Paris is 10:45 AM
```

Suppose the user inputs "New York" as the city. Your program should connect to the API, retrieve the timezone information for New York, and calculate the local time in New York. The output should look something like this:

```
The local time in New York is 4:45 AM
```

## Requirements

- Your program must take as input the name of a city in the world.
- Your program must connect to an API to retrieve timezone information.
- Your program must use the timezone information to calculate the local time in the given city.
- Your program must output the local time in the given city in a readable format.

## Python Solution

```python
import requests
import datetime
import pytz

def get_local_time(city):
    url = f"http://worldtimeapi.org/api/timezone/Europe/{city}"
    response = requests.get(url)
    if response.status_code == 404:
        return f"Error: {city} not found"
    data = response.json()
    tz = pytz.timezone(data['timezone'])
    local_time = datetime.datetime.now(tz=tz)
    return f"The local time in {city} is {local_time.strftime('%I:%M %p')}"

```

## Testing

```python
import unittest

class TestGetLocalTime(unittest.TestCase):
    
    def test_valid_city(self):
        self.assertEqual(get_local_time('Paris'), 'The local time in Paris is 04:45 PM')
        self.assertEqual(get_local_time('New_York'), 'The local time in New_York is 10:45 AM')
        self.assertEqual(get_local_time('Sydney'), 'The local time in Sydney is 12:45 AM')
        
    def test_invalid_city(self):
        self.assertEqual(get_local_time('Fake_City'), 'Error: Fake_City not found')
        
if __name__ == '__main__':
    unittest.main()
```

## Summary

In this coding challenge, you developed a program that can retrieve the local time of any city in the world, given its name. You used an API that provides timezone information for cities around the world and calculated the local time in the given city. You also wrote unit tests to ensure that your program works as expected.

**Comment by CALMorACT** [comment]
4.18 李昊
