### ISSUE TITLE
challenge-long-word-counter

### ISSUE THREAD

**Issue by jiaosenvip** [labex-labs/scenarios#405]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Long Word Counter
- **Suggest Steps 建议步骤数**: 1
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/str`**
- **`python/for_loop`**
- **`python/function_basic`**
- **`python/if_else`**

**Comment by jiaosenvip** [comment]
# Long Word Counter

## Introduction

In this challenge, you will implement a function that counts the number of words in a given string that are longer than a specific length. You will write this function using basic Python syntax and string manipulation techniques.

## Problem Description

Write a function called `count_long_words` that takes two arguments: a string and an integer. The function should return the number of words in the string that are longer than the given integer. You can assume that the string only contains alphabetic characters and spaces.

## Requirements
- The input string should not be modified
- The function should return an integer
- The function should ignore punctuation and other non-alphabetic characters
- The function should be case-insensitive

## Example Usage

```python
text = "The quick brown fox jumps over the lazy dog"
count = count_long_words(text, 4)
print(count) # 5
```

## Code Template

```python
def count_long_words(text, length):
    # Your code here
    pass
```

## Summary

In this challenge, you learned how to write a Python function that counts the number of words in a given string that are longer than a specific length. You also learned how to manipulate strings in Python.

## Answer

```python
def count_long_words(text, length):
    words = text.split()
    count = 0
    for word in words:
        word = word.strip('.,;:!?')
        if len(word) > length:
            count += 1
    return count
```

## Checker (unittest)

```python
import unittest

class TestCountLongWords(unittest.TestCase):
    def test_count_long_words(self):
        text = "The quick brown fox jumps over the lazy dog"
        self.assertEqual(count_long_words(text, 4), 5)
        
        text = "A cat in the hat"
        self.assertEqual(count_long_words(text, 3), 2)
        
        text = "Python is a great language for data science"
        self.assertEqual(count_long_words(text, 5), 2)

if __name__ == '__main__':
    unittest.main()
```

**Comment by Beichen-Ma** [comment]
@jiaosenvip  answer或者test有问题，example的输出也不对。check一下

**Comment by jiaosenvip** [comment]
> @jiaosenvip answer或者test有问题，example的输出也不对。check一下

已更新
