### ISSUE TITLE
lab-kubernetes-dashboard

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#418]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Kubernetes Dashboard
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/create`
- `kubernetes/edit`
- `kubernetes/get`
- `kubernetes/k8s_dashboard`

**Comment by joker-bai** [comment]
# Kubernetes Dashboard

Kubernetes Dashboard is a web-based user interface for managing and monitoring Kubernetes clusters. It provides an easy way to deploy and manage applications, as well as view and analyze cluster resources. In this lab, we will walk through the steps to deploy and use Kubernetes Dashboard.

## Prerequisites

Before starting this lab, you should have a Kubernetes cluster up and running. You should also have `kubectl` installed and configured to access the cluster.

## Step 1: Deploying Kubernetes Dashboard

In this step, we will deploy Kubernetes Dashboard to our cluster.

1. Run the following command to deploy the Kubernetes Dashboard:

   ```bash
   kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml
   ```

   This will create all of the necessary resources for the dashboard to run, including a deployment, a service, and a role-based access control (RBAC) configuration.

2. Verify that the dashboard is running by running the following command:

   ```bash
   kubectl get pods -n kubernetes-dashboard
   ```

   This will show you the status of the Kubernetes Dashboard pod. Wait until the pod is in the `Running` state.

## Step 2: Creating a Service Account and Cluster Role Binding

In this step, we will create a service account and cluster role binding to allow us to access the Kubernetes Dashboard.

1. Create a file named `dashboard-admin.yaml` with the following contents:

   ```yaml
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: admin-user
     namespace: kubernetes-dashboard
   ---
   apiVersion: rbac.authorization.k8s.io/v1
   kind: ClusterRoleBinding
   metadata:
     name: admin-user
   roleRef:
     apiGroup: rbac.authorization.k8s.io
     kind: ClusterRole
     name: cluster-admin
   subjects:
   - kind: ServiceAccount
     name: admin-user
     namespace: kubernetes-dashboard
   ```

   This file creates a service account named `admin-user` and a cluster role binding that grants it cluster-admin privileges.

2. Apply the changes by running the following command:

   ```shell
   kubectl apply -f dashboard-admin.yaml
   ```

## Step 3: Accessing Kubernetes Dashboard

In this step, we will access the Kubernetes Dashboard using a web browser.

1. Now we need to find the token we can use to log in. Execute the following command:

   ```bash
   kubectl -n kubernetes-dashboard create token admin-user
   ```

   This will output a token that you can use to log in to the Kubernetes Dashboard.

2. Use the following command to change the service type of the kubernetes dashboard to `NodePort`.
	
   ```bash
   kubectl edit service -n kubernetes-dashboard kubernetes-dashboard
   ```

   Then use the following command to get the nodeport of the kubernetes dashboard.

   ```bash
   kubectl get service -n kubernetes-dashboard
   ```

3. Use the following command to get the kubernetes node ip address.

   ```bash
   kubectl get node -o wide
   ```
   
   The data labeled as `INTERNAL-IP` is the IP address of the node.

3. Open a web browser and navigate to `http://<node-ip>:<node-port>`.

   Replace `<node-ip>` with the node IP address and Replace `<node-port>` with the kubernetes dashboard node port.

3. Select the `Token` option, and enter the access token from step 1 when prompted.

4. You should now be logged in to the Kubernetes Dashboard, and can explore the various features and resources available.

## Summary

In this lab, we learned how to deploy and use Kubernetes Dashboard to manage and monitor a Kubernetes cluster. We deployed the dashboard, created a service account and cluster role binding to allow us to access it, and accessed the dashboard using a web browser. With Kubernetes Dashboard, you can easily deploy and manage applications, monitor cluster resources, and perform other administrative tasks.

**Comment by qazxswery** [comment]
2023.4.20

**Comment by qazxswery** [comment]
![结果](https://user-images.githubusercontent.com/96094543/233625322-7b01a885-5c90-4cb5-882a-aea06a17e3c9.png)
我尽力了
