### ISSUE TITLE
challenge-grocery-list-generator

### ISSUE THREAD

**Issue by jiaosenvip** [labex-labs/scenarios#429]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Grocery List Generator
- **Suggest Steps 建议步骤数**: 1
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/data_types`**
- `python/for_loop`
- `python/set`
- `python/list`
- `python/function_basic`

**Comment by jiaosenvip** [comment]
# Python Grocery List Generator

## Introduction:
You are helping a friend who is starting a new healthy eating plan. They have asked you to create a Python program that will generate a grocery list based on their meal plan for the week. Your task is to create a program that will take in their meal plan and generate a grocery list of all the ingredients needed for the week.

## Problem Description:
You will be given a list of tuples, where each tuple represents a meal. Each tuple contains the following information:
- the name of the meal (a string)
- a list of ingredients (a list of strings)

Your program should process this data and provide the following information:
- a list of all the unique ingredients needed for the week

## Requirements:
- Define a function `generate_grocery_list(meal_plan: List[Tuple[str, List[str]]]) -> List[str]` that takes in a list of meal plans and returns a list of all the unique ingredients needed for the week.
- The function should be able to handle an empty meal plan and return an empty list.
- The function should use the `zip` function to combine the ingredients from all meals.
- The function should use a set to get the unique ingredients.

## Example Usage:
```
meal_plan = [('Spaghetti Bolognese', ['spaghetti', 'ground beef', 'tomato sauce', 'onion', 'garlic', 'parmesan cheese']),
             ('Chicken Stir Fry', ['chicken breast', 'broccoli', 'carrots', 'soy sauce', 'rice']),
             ('Caesar Salad', ['romaine lettuce', 'croutons', 'parmesan cheese', 'caesar dressing'])]
generate_grocery_list(meal_plan)
```
Output:
```
['garlic', 'onion', 'parmesan cheese', 'carrots', 'broccoli', 'tomato sauce', 'romaine lettuce', 'rice', 'soy sauce', 'spaghetti', 'croutons', 'chicken breast']
```

## Code Template:
```python
from typing import List, Tuple

def generate_grocery_list(meal_plan: List[Tuple[str, List[str]]]) -> List[str]:
    unique_ingredients = set()
    
    # TODO: Process meal plan and fill in the ingredients
    
    return list(unique_ingredients)
```

## Summary:
You need to create a Python program that generates a grocery list based on a meal plan. The program should handle an empty meal plan, use the `zip` function to combine the ingredients from all meals, and use a set to get the unique ingredients.

## Answer:
```python
from typing import List, Tuple

def generate_grocery_list(meal_plan: List[Tuple[str, List[str]]]) -> List[str]:
    unique_ingredients = set()
    
    for meal in meal_plan:
        unique_ingredients.update(meal[1])
        
    return list(unique_ingredients)
```

## Checker:
```python
import unittest
from typing import List, Tuple

class TestGenerateGroceryList(unittest.TestCase):

    def test_empty_meal_plan(self):
        meal_plan = []
        expected_output = []
        self.assertEqual(generate_grocery_list(meal_plan), expected_output)

    def test_valid_meal_plan(self):
        meal_plan = [('Spaghetti Bolognese', ['spaghetti', 'ground beef', 'tomato sauce', 'onion', 'garlic', 'parmesan cheese']),
                     ('Chicken Stir Fry', ['chicken breast', 'broccoli', 'carrots', 'soy sauce', 'rice']),
                     ('Caesar Salad', ['romaine lettuce', 'croutons', 'parmesan cheese', 'caesar dressing'])]
        expected_output = ['garlic', 'onion', 'parmesan cheese', 'carrots', 'broccoli', 'tomato sauce', 'romaine lettuce', 'rice', 'soy sauce', 'spaghetti', 'croutons', 'chicken breast']
        self.assertEqual(generate_grocery_list(meal_plan), expected_output)

if __name__ == '__main__':
    unittest.main()
```

**Comment by Beichen-Ma** [comment]
@jiaosenvip  requirements里说要用zip function，answer里貌似没有。

**Comment by jiaosenvip** [comment]
> @jiaosenvip requirements里说要用zip function，answer里貌似没有。

那条要求删掉吧。unittest 也没检测是否使用。
