### ISSUE TITLE
challenge-recipe-recommendation

### ISSUE THREAD

**Issue by jiaosenvip** [labex-labs/scenarios#432]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Recipe Recommendation
- **Suggest Steps 建议步骤数**: 1
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/data_types`**
- `python/for_loop`
- `python/function_basic`

**Comment by jiaosenvip** [comment]
# Recipe Recommendation

## Introduction

You are helping a friend who loves to cook and experiment with different recipes. They have asked you to create a program that will recommend recipes based on the ingredients they have on hand. Your task is to create a program that will take in a list of ingredients and return a list of recommended recipes.

## Problem Description

You need to create a Python program that recommends recipes based on the ingredients provided. You will be provided with a list of dictionaries, where each dictionary contains the following information:
- the name of the recipe (a string)
- a list of ingredients (a list of strings)

Your program should process this data and provide the following information:
- a list of all the recipes that can be made with the ingredients provided

## Requirements

- Define a function `recommend_recipes(ingredients: List[str], recipe_list: List[Dict[str, List[str]]]) -> List[str]` that takes in a list of ingredients and a list of recipes and returns a list of all the recipes that can be made with the ingredients provided.
- The function should return an empty list if no recipes can be made with the ingredients provided.
- The function should match recipes based on any ingredient being present in the list of ingredients provided.

## Example Usage

```
recipe_list = [{'name': 'Spaghetti Bolognese', 'ingredients': ['spaghetti', 'ground beef', 'tomato sauce', 'onion', 'garlic']},
               {'name': 'Chicken Alfredo', 'ingredients': ['fettuccine', 'chicken breast', 'heavy cream', 'butter', 'parmesan cheese']},
               {'name': 'Vegetable Stir Fry', 'ingredients': ['rice', 'broccoli', 'carrots', 'onion', 'garlic', 'soy sauce']}]

recommend_recipes(['spaghetti', 'tomato sauce', 'garlic'], recipe_list)
# Output: ['Spaghetti Bolognese']

recommend_recipes(['spaghetti', 'carrots'], recipe_list)
# Output: []

recommend_recipes(['rice', 'broccoli', 'soy sauce'], recipe_list)
# Output: ['Vegetable Stir Fry']
```

## Code Template

```python
from typing import List, Dict

def recommend_recipes(ingredients: List[str], recipe_list: List[Dict[str, List[str]]]) -> List[str]:
    # TODO: Implement recipe recommendation
    pass
```

## Summary

You need to create a Python program that recommends recipes based on the ingredients provided. The program should return an empty list if no recipes can be made with the ingredients provided.

## Answer

```python
from typing import List, Dict

def recommend_recipes(ingredients: List[str], recipe_list: List[Dict[str, List[str]]]) -> List[str]:
    recommended_recipes = []
    
    for recipe in recipe_list:
        recipe_ingredients = recipe['ingredients']
        
        if all(ingredient in ingredients for ingredient in recipe_ingredients):
            recommended_recipes.append(recipe['name'])
    
    return recommended_recipes
```

## Checker

```python
import unittest

class TestRecipeRecommendation(unittest.TestCase):

    def test_no_match(self):
        recipe_list = [{'name': 'Spaghetti Bolognese', 'ingredients': ['spaghetti', 'ground beef', 'tomato sauce', 'onion', 'garlic']},
                       {'name': 'Chicken Alfredo', 'ingredients': ['fettuccine', 'chicken breast', 'heavy cream', 'butter', 'parmesan cheese']},
                       {'name': 'Vegetable Stir Fry', 'ingredients': ['rice', 'broccoli', 'carrots', 'onion', 'garlic', 'soy sauce']}]
        self.assertEqual(recommend_recipes(['spaghetti', 'carrots'], recipe_list), [])

    def test_partial_match(self):
        recipe_list = [{'name': 'Spaghetti Bolognese', 'ingredients': ['spaghetti', 'ground beef', 'tomato sauce', 'onion', 'garlic']},
                       {'name': 'Chicken Alfredo', 'ingredients': ['fettuccine', 'chicken breast', 'heavy cream', 'butter', 'parmesan cheese']},
                       {'name': 'Vegetable Stir Fry', 'ingredients': ['rice', 'broccoli', 'carrots', 'onion', 'garlic', 'soy sauce']}]
        self.assertEqual(recommend_recipes(['spaghetti', 'tomato sauce', 'garlic'], recipe_list), ['Spaghetti Bolognese'])

    def test_exact_match(self):
        recipe_list = [{'name': 'Spaghetti Bolognese', 'ingredients': ['spaghetti', 'ground beef', 'tomato sauce', 'onion', 'garlic']},
                       {'name': 'Chicken Alfredo', 'ingredients': ['fettuccine', 'chicken breast', 'heavy cream', 'butter', 'parmesan cheese']},
                       {'name': 'Vegetable Stir Fry', 'ingredients': ['rice', 'broccoli', 'carrots', 'onion', 'garlic', 'soy sauce']}]
        self.assertEqual(recommend_recipes(['rice', 'broccoli', 'soy sauce'], recipe_list), ['Vegetable Stir Fry'])

if __name__ == '__main__':
    unittest.main()
```

**Comment by Beichen-Ma** [comment]
@jiaosenvip  用Answer跑unit test三个tests全是返回空列表，貌似answer没有达到requirements
