### ISSUE TITLE
lab-git-branch-basic-operations

### ISSUE THREAD

**Issue by thenicebro** [labex-labs/scenarios#435]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Git Branch Basic Operations
- **Suggest Steps 建议步骤数**: 4
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`git/branch`**
- **`git/checkout`**
- **`git/merge`**
- **`git/log`**

**Comment by thenicebro** [comment]
# Branches of Git

In this lab, you will learn how to use Git's `branch`, `checkout`, and `merge` commands. These commands are essential for working collaboratively on code with Git, as they allow developers to work on different parts of the code-base without interfering with each other's work.

## Introduction

Git is a powerful tool for managing code, allowing developers to collaborate on code and track changes over time. One of the key features of Git is its support for branching, which allows developers to create separate copies of the code-base that can be modified independently of the main code-base. 

This is useful when working on new features or fixing bugs, as it allows developers to experiment and make changes without affecting the main code-base.

In this lab, we will cover the basics of branching with Git, including creating new branches, switching between branches, and merging changes from one branch to another.

## Working directory

All operations need to be done in the `~/myrepo` directory, so as a first step you should go into the `~/myrepo` directory.

## Step 1: Creating a New Branch

The `branch` command is used to create a new branch in Git.

To create a new branch, use the following command:

```bash
git branch my-branch
```

This will create a new branch that is identical to the current branch.

## Step 2: Switching between Git Branches

The `checkout` command is used to switch between different branches in Git.

To switch to a different branch, use the following command:

```bash
git checkout other-branch
# You need to create this branch in the startup script.
```

This will replace the code-base with the version of the code on that branch.

## Step 3: Merging Git Branches

The `merge` command is used to combine changes from one branch into another branch.

To merge changes from one branch into another branch, use the following command:

```bash
git merge new-branch
# You need to create this branch in the startup script.
```

This will merge the `new-branch` branch into the current branch(other-branch).

## Conclusion

By completing this lab, you should now be comfortable creating and switching between branches, as well as merging changes from one branch to another. These are essential skills for collaborating on code with Git, and mastering them will help you become a more effective and efficient developer.

**Comment by CALMorACT** [comment]
4.17 李昊

**Comment by huhuhang** [comment]
> 4.17 李昊

不要认领 Assignees 非空的 Issue。

**Comment by huhuhang** [comment]
@thenicebro 这个 Issue，你叫 Branches of Git 这个名字，感觉内容内容有点单薄。因为这个名字很大。

1. 继续叫 Branches of Git，其实改成 Git Branch 更好。但是补充更多的 steps，例如删除分支，远程分支等，让这个 lab 更全面一些。
2. 换个小一点的名字，只围绕你设计的内容展开。

**Comment by thenicebro** [comment]
# Git Branch Basic Operation

This lab is designed to teach you how to use git commands such as `branch`, `checkout`, `merge`, and `log`. There are four steps, each of which corresponds to a specific command.

## Creating Branches

In Git, a branch is a separate line of development that allows you to work on a feature or bug fix without affecting the main codebase. To create a new branch, use the `branch` command followed by the name of the new branch:

```bash
git branch new-feature
```

This command creates a new branch named `new-feature` that is identical to the current branch. You can now switch to this new branch using the `checkout` command:

```bash
git checkout new-feature
```

## Renaming and Deleting Branches

If you want to rename a branch, use the `branch` command with the `-m` option followed by the new name:

```bash
git branch -m old-name new-name
```

To delete a branch, use the `branch` command with the `-d` option followed by the name of the branch you want to delete:

```bash
git branch -d branch-to-delete
```

## Merging Branches

Once you have made changes to a feature branch, you can merge it back into the main codebase using the `merge` command. First, switch back to the main branch:

```bash
git checkout main
```

Then, use the `merge` command followed by the name of the branch you want to merge:

```bash
git merge new-feature
```

This command will merge the changes from `new-feature` into the `main` branch.

## Viewing Branch History

The `log` command allows you to view the commit history of a branch:

```bash
git log
```

This command shows you the commit history for the current branch, including the commit message, author, and timestamp.

## Conclusion

In this lab, you learned how to create, rename, delete, merge, and view the commit history of branches using Git commands. By using these commands, you can work on features and bug fixes in separate branches, collaborate with other developers, and maintain a clean and organized codebase.
