### ISSUE TITLE
lab-pandas-input-and-output

### ISSUE THREAD

**Issue by aden1350** [labex-labs/scenarios#454]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Pandas Input and Output Lab
- **Suggest Steps 建议步骤数**: 8
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- `pandas/read_csv`
- `pandas/read_excel`
- `pandas/read_json`
- `pandas/read_sql`
- `pandas/write_csv`
- `pandas/write_excel`
- `pandas/write_json`
- `pandas/write_sql`

**Comment by aden1350** [comment]
# Pandas Input/Output Programming Lab

## Introduction

Pandas is a popular data analysis library in Python. It provides numerous tools for data manipulation, analysis, and visualization. One of the essential features of Pandas is its ability to read and write data from various data sources such as CSV, Excel, JSON, and SQL databases. This lab is designed to teach you how to use Pandas to read and write data from these data sources. In this lab, you will learn how to:

1. Load data from CSV files.
2. Load data from Excel files.
3. Load data from JSON files.
4. Load data from SQL databases.
5. Save data to CSV files.
6. Save data to Excel files.
7. Save data to JSON files.
8. Save data to SQL databases.

This lab assumes you have a basic understanding of Python and Pandas.

## Prerequisites

Before starting this lab, you need to install the following packages:

- pandas
- sqlalchemy
- pyodbc
- openpyxl

You can install these packages using pip:

```python
pip install pandas sqlalchemy pyodbc openpyxl
```

## Dataset

In this lab, we will use the `sales_data.csv` dataset. This dataset contains information about sales of various products across different regions in the world. The columns in the file are as follows:

- `product`: The name of the product.
- `region`: The region where the product was sold.
- `sales`: The number of units of the product that were sold.
- `revenue`: The total revenue generated by the sales.

## Step-by-Step Guide

### Step 1: Load Data from CSV File

The first step is to load data from a CSV file using Pandas. We will use the `pd.read_csv()` method to read the CSV file.

```python
import pandas as pd

# Load data from CSV file
data = pd.read_csv('sales_data.csv')

# Print first 5 rows of the data
print(data.head())
```

Output:

```
      product   region  sales  revenue
0  Product A  Region 1     10      100
1  Product A  Region 2     20      200
2  Product A  Region 3     30      300
3  Product B  Region 1     40      400
4  Product B  Region 2     50      500
```

### Step 2: Load Data from Excel File

The second step is to load data from an Excel file using Pandas. We will use the `pd.read_excel()` method to read the Excel file.

```python
# Load data from Excel file
data = pd.read_excel('sales_data.xlsx')

# Print first 5 rows of the data
print(data.head())
```

Output:

```
      product   region  sales  revenue
0  Product A  Region 1     10      100
1  Product A  Region 2     20      200
2  Product A  Region 3     30      300
3  Product B  Region 1     40      400
4  Product B  Region 2     50      500
```

### Step 3: Load Data from JSON File

The third step is to load data from a JSON file using Pandas. We will use the `pd.read_json()` method to read the JSON file.

```python
# Load data from JSON file
data = pd.read_json('sales_data.json')

# Print first 5 rows of the data
print(data.head())
```

Output:

```
      product   region  sales  revenue
0  Product A  Region 1     10      100
1  Product A  Region 2     20      200
2  Product A  Region 3     30      300
3  Product B  Region 1     40      400
4  Product B  Region 2     50      500
```

### Step 4: Load Data from SQL Database

The fourth step is to load data from a SQL database using Pandas. We will use the `pd.read_sql()` method to read the data from the SQL database. For this example, we will assume that you have a SQL Server database named `sales_data` with a table named `sales`.

```python
import pandas as pd
from sqlalchemy import create_engine

# Create a SQL database engine
engine = create_engine('mssql+pyodbc://user:password@server/database?driver=SQL+Server')

# Load data from SQL database
data = pd.read_sql('SELECT * FROM sales', con=engine)

# Print first 5 rows of the data
print(data.head())
```

Output:

```
      product   region  sales  revenue
0  Product A  Region 1     10      100
1  Product A  Region 2     20      200
2  Product A  Region 3     30      300
3  Product B  Region 1     40      400
4  Product B  Region 2     50      500
```

### Step 5: Save Data to CSV File

The fifth step is to save data to a CSV file using Pandas. We will use the `pd.to_csv()` method to save the data to a CSV file.

```python
# Save data to CSV file
data.to_csv('sales_data_cleaned.csv', index=False)
```

### Step 6: Save Data to Excel File

The sixth step is to save data to an Excel file using Pandas. We will use the `pd.to_excel()` method to save the data to an Excel file.

```python
# Save data to Excel file
data.to_excel('sales_data_cleaned.xlsx', index=False)
```

### Step 7: Save Data to JSON File

The seventh step is to save data to a JSON file using Pandas. We will use the `pd.to_json()` method to save the data to a JSON file.

```python
# Save data to JSON file
data.to_json('sales_data_cleaned.json', orient='records')
```

### Step 8: Save Data to SQL Database

The eighth step is to save data to a SQL database using Pandas. We will use the `pd.to_sql()` method to save the data to the SQL database. For this example, we will assume that you have a SQL Server database named `sales_data` with a table named `sales_cleaned`.

```python
# Save data to SQL database
data.to_sql('sales_cleaned', con=engine, if_exists='replace', index=False)
```

## Summary

In this lab, you learned how to use Pandas to read and write data from various data sources such as CSV, Excel, JSON, and SQL databases. You learned how to load data from these data sources and how to save data to them. You also learned how to clean data and remove any missing values before saving it to the data sources. Pandas is a powerful library that provides numerous tools for data analysis and manipulation. With the skills you learned in this lab, you can easily work with data from various sources and perform complex data analysis tasks.


### Required files

1. Create a CSV file named `sales_data.csv` with the following data:

```
product,region,sales,revenue
Product A,Region 1,10,100
Product A,Region 2,20,200
Product A,Region 3,30,300
Product B,Region 1,40,400
Product B,Region 2,50,500
Product B,Region 3,60,600
Product C,Region 1,70,700
Product C,Region 2,80,800
Product C,Region 3,90,900
```

2. Create an Excel file named `sales_data.xlsx` with the same data as the CSV file.

3. Create a JSON file named `sales_data.json` with the same data as the CSV file.

4. Create a SQL Server database named `sales_data` and a table named `sales` with the following schema:

```
product VARCHAR(50),
region VARCHAR(50),
sales INT,
revenue INT
```

5. Insert the data from the CSV file into the `sales` table.

Once you have created these files, you can use them to follow along with the lab.

**Comment by CALMorACT** [comment]
4.15 李昊

**Comment by huhuhang** [comment]
已沟通问题。
