### ISSUE TITLE
lab-getting-started-with-videos

### ISSUE THREAD

**Issue by GodsDusk** [labex-labs/scenarios#512]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Getting Started with Videos
- **Suggest Steps 建议步骤数**:2
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`opencv/video_capture`**
- **`opencv/fourcc`**
- **`opencv/video_writer`**

**Comment by GodsDusk** [comment]
# Getting Started with Videos

Welcome to this tutorial on how to get started with videos using OpenCV-Python! OpenCV (Open Source Computer Vision) is a powerful library designed for image processing, machine learning, and computer vision applications. In this tutorial, we'll be focusing on how to work with videos in OpenCV-Python.

## Reading and Displaying a Video

To capture a video, you need to create a `VideoCapture` object. Here's an example of how to read and display a video:

```python
import cv2

# Create a VideoCapture object
cap = cv2.VideoCapture('video.mp4')

while True:
    # Read a frame from the video
    ret, frame = cap.read()

    if ret:
        # Display the frame
        cv2.imshow('Video', frame)

    # Wait for key press
    if cv2.waitKey(1) == ord('q'):
        break

# Release the VideoCapture object and close all windows
cap.release()
cv2.destroyAllWindows()
```

In this example, we create a `VideoCapture` object by passing the path of the video file to be read. Then, we use a `while` loop to read each frame of the video using the `read()` method. If the frame is successfully read, we display it using the `imshow()` method. Finally, we wait for a key press to exit the loop, release the `VideoCapture` object, and destroy all windows.

## Writing and Saving a Video

To write and save a video, you need to create a `VideoWriter` object. Here's an example of how to write and save a video:

```python
import cv2

# Create a VideoCapture object
cap = cv2.VideoCapture('video.mp4')

# Get the video frame size and frame rate
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

# Create a VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi', fourcc, fps, (width, height))

while True:
    # Read a frame from the video
    ret, frame = cap.read()

    if ret:
        # Process the frame
        # ...

        # Write the processed frame to the output video
        out.write(frame)

    else:
        break

# Release the VideoCapture and VideoWriter objects
cap.release()
out.release()
```

In this example, we create a `VideoCapture` object by passing the path of the video file to be read. Then, we get the video frame size and frame rate using the `get()` method. Next, we create a `VideoWriter` object by passing the output file name, fourcc code, frame rate, and frame size. The fourcc code is a four-byte code used to specify the video codec. In this example, we use the XVID codec.

We then use a `while` loop to read each frame of the video using the `read()` method. If the frame is successfully read, we process it (e.g., apply filters) and write it to the output video using the `write()` method of the `VideoWriter` object. Finally, we release the `VideoCapture` and `VideoWriter` objects.

## Conclusion

Congratulations! You have now learned how to read, display, write, and save videos using OpenCV-Python. With these basic skills, you can start exploring more advanced computer vision techniques and applications.

Feel free to expand on this tutorial by trying out different video formats, applying filters to the frames, or experimenting with object tracking and detection. The possibilities are endless!

**Comment by GodsDusk** [comment]
webide环境无法使用gui，请认领人将实验步骤中的imshow都换为imwrite，另外自备视频要注意版权问题，建议使用 CC0 的无版权图片制作视频

**Comment by huhuhang** [comment]
> webide环境无法使用gui，请认领人将实验步骤中的imshow都换为imwrite，另外自备视频要注意版权问题，建议使用 CC0 的无版权图片制作视频

建议给出示例视频……

**Comment by GodsDusk** [comment]
演示视频

https://user-images.githubusercontent.com/13726533/233232577-a1104c0b-b6c7-471d-bf6e-4ca3f46f5198.mp4

**Comment by huduo0812** [comment]
胡舵 04.28
