### ISSUE TITLE
challenge-data-analyst-in-clothing-store

### ISSUE THREAD

**Issue by aden1350** [labex-labs/scenarios#534]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Company Sales
- **Suggest Steps 建议步骤数**: 4
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- `pandas/read_csv`
- `pandas/plot`
- `pandas/dataframe`

**Comment by aden1350** [comment]
# Data Analyst in Fashionista

## Introduction

You are a data analyst working for a clothing company called Fashionista. Your team has been tasked with analyzing the company's sales data to identify trends and patterns that can help the company make data-driven decisions. Your team has been provided with a large dataset containing information about the company's sales, including the products sold, the date and time of sale, the location of sale, and the price of the product. You will be using Pandas, a popular Python library for data manipulation and analysis, to perform your analysis.

## Goal

Your goal is to use Pandas to clean and analyze the sales data provided by Fashionista, and to present your findings to the company's executives in a clear and concise manner.

## Requirements

The challenge consists of several steps, each building on the previous step. The steps are as follows:

### Step 1: Loading and inspecting the data

In this step, you will load the data from a CSV file using Pandas, and then inspect the data to get an understanding of its structure and content.

#### Requirements:

1. Load the data from the provided CSV file using Pandas
2. Display the first 5 rows of the data to inspect its structure
3. Display the last 5 rows of the data to ensure that there are no missing values
4. Display the shape of the data to get an idea of its size

#### Solution:

```python
import pandas as pd

# Load the data from the CSV file
sales_data = pd.read_csv('sales_data.csv')

# Display the first 5 rows of the data
print(sales_data.head())

# Display the last 5 rows of the data
print(sales_data.tail())

# Display the shape of the data
print(sales_data.shape)
```

### Step 2: Cleaning the data

In this step, you will clean the data by removing any missing values, and converting the data types of some columns.

#### Requirements:

1. Remove any rows that contain missing values
2. Convert the `date` column to a `datetime` data type
3. Convert the `product_code` column to a categorical data type

#### Solution:

```python
# Remove any rows that contain missing values
sales_data.dropna(inplace=True)

# Convert the date column to a datetime data type
sales_data['date'] = pd.to_datetime(sales_data['date'])

# Convert the product_code column to a categorical data type
sales_data['product_code'] = pd.Categorical(sales_data['product_code'])
```

### Step 3: Grouping and Aggregating the data

In this step, you will use Pandas to group the data by different variables and compute some aggregate statistics.

#### Requirements:

1. Group the data by `location` and compute the total sales for each location
2. Group the data by `product_code` and compute the total sales for each product
3. Group the data by `date` and compute the total sales for each day

#### Solution:

```python
# Group the data by location and compute the total sales for each location
sales_by_location = sales_data.groupby('location')['price'].sum()

# Group the data by product_code and compute the total sales for each product
sales_by_product = sales_data.groupby('product_code')['price'].sum()

# Group the data by date and compute the total sales for each day
sales_by_day = sales_data.groupby('date')['price'].sum()
```

### Step 4: Visualizing the data

In this step, you will use Pandas and Matplotlib to create some visualizations of the sales data.

#### Requirements:

1. Create a bar chart showing the total sales for each location
2. Create a pie chart showing the percentage of total sales for each product
3. Create a line chart showing the daily sales over time

#### Solution:

```python
import matplotlib.pyplot as plt

# Create a bar chart showing the total sales for each location
sales_by_location.plot(kind='bar')
plt.title('Total Sales by Location')
plt.xlabel('Location')
plt.ylabel('Total Sales')
plt.show()

# Create a pie chart showing the percentage of total sales for each product
sales_by_product.plot(kind='pie')
plt.title('Percentage of Total Sales by Product')
plt.ylabel('')
plt.show()

# Create a line chart showing the daily sales over time
sales_by_day.plot(kind='line')
plt.title('Daily Sales over Time')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.show()
```

## Summary

In this programming challenge, you used Pandas to load, clean, aggregate and visualize sales data for a clothing company called Fashionista. You started by loading the data from a CSV file and inspecting its structure and content. You then cleaned the data by removing any missing values and converting the data types of some columns. You aggregated the data by grouping it by different variables and computing some aggregate statistics such as total sales for each location, product, and day. Finally, you used Pandas and Matplotlib to create some visualizations of the sales data such as bar chart, pie chart, and line chart.

By completing this challenge, you gained a better understanding of how to use Pandas to manipulate and analyze data, which is a valuable skill for any data analyst or data scientist.

##Unitest code

```python
import pandas as pd
import numpy as np
import unittest

# Step 1 Unit Test
class TestStep1(unittest.TestCase):
    def setUp(self):
        self.sales_data = pd.read_csv('sales_data.csv')
    
    def test_first_five_rows(self):
        self.assertEqual(self.sales_data.head().shape, (5, 6))
    
    def test_last_five_rows(self):
        self.assertEqual(self.sales_data.tail().shape, (5, 6))
    
    def test_shape(self):
        self.assertEqual(self.sales_data.shape, (1000, 6))


# Step 2 Unit Test
class TestStep2(unittest.TestCase):
    def setUp(self):
        self.sales_data = pd.read_csv('sales_data.csv').dropna()
        self.sales_data['date'] = pd.to_datetime(self.sales_data['date'])
        self.sales_data['product_code'] = pd.Categorical(self.sales_data['product_code'])
    
    def test_missing_values(self):
        self.assertEqual(self.sales_data.isnull().sum().sum(), 0)
    
    def test_date_column_type(self):
        self.assertIsInstance(self.sales_data['date'].iloc[0], pd.Timestamp)
    
    def test_product_code_column_type(self):
        self.assertIsInstance(self.sales_data['product_code'].iloc[0], pd.Categorical)


# Step 3 Unit Test
class TestStep3(unittest.TestCase):
    def setUp(self):
        self.sales_data = pd.read_csv('sales_data.csv').dropna()
        self.sales_data['date'] = pd.to_datetime(self.sales_data['date'])
        self.sales_data['product_code'] = pd.Categorical(self.sales_data['product_code'])
    
    def test_sales_by_location_shape(self):
        sales_by_location = self.sales_data.groupby('location')['price'].sum()
        self.assertEqual(sales_by_location.shape, (4,))
    
    def test_sales_by_location_sum(self):
        sales_by_location = self.sales_data.groupby('location')['price'].sum()
        self.assertEqual(sales_by_location.sum(), self.sales_data['price'].sum())
    
    def test_sales_by_product_shape(self):
        sales_by_product = self.sales_data.groupby('product_code')['price'].sum()
        self.assertEqual(sales_by_product.shape, (6,))
    
    def test_sales_by_product_sum(self):
        sales_by_product = self.sales_data.groupby('product_code')['price'].sum()
        self.assertEqual(sales_by_product.sum(), self.sales_data['price'].sum())
    
    def test_sales_by_day_shape(self):
        sales_by_day = self.sales_data.groupby('date')['price'].sum()
        self.assertEqual(sales_by_day.shape, (30,))
    
    def test_sales_by_day_sum(self):
        sales_by_day = self.sales_data.groupby('date')['price'].sum()
        self.assertEqual(sales_by_day.sum(), self.sales_data['price'].sum())


# Step 4 Unit Test
class TestStep4(unittest.TestCase):
    def setUp(self):
        self.sales_data = pd.read_csv('sales_data.csv').dropna()
        self.sales_data['date'] = pd.to_datetime(self.sales_data['date'])
        self.sales_data['product_code'] = pd.Categorical(self.sales_data['product_code'])
    
    def test_bar_chart_type(self):
        sales_by_location = self.sales_data.groupby('location')['price'].sum()
        ax = sales_by_location.plot(kind='bar')
        self.assertIsInstance(ax, type(pd.DataFrame().plot()))
    
    def test_pie_chart_type(self):
        sales_by_product = self.sales_data.groupby('product_code')['price'].sum()
        ax = sales_by_product.plot(kind='pie')
        self.assertIsInstance(ax, type(pd.DataFrame().plot()))

    def test_line_chart_type(self):
        sales_by_day = self.sales_data.groupby('date')['price'].sum()
        ax = sales_by_day.plot(kind='line')
        self.assertIsInstance(ax, type(pd.DataFrame().plot()))

if **name** == '**main**':
unittest.main()

```

**Comment by huhuhang** [comment]
这个 issue 内容有问题，已经语音留言，可以先自己试试看实现成 challenge。最后再反向修改这个 issue 的内容。
