### ISSUE TITLE
challenge-docker-network-with-compose

### ISSUE THREAD

**Issue by GuoJiang-yw** [labex-labs/scenarios#604]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Docker Network  With Compose
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`docker/network`**
- `docker/run`
- `docker/exec`

**Comment by GuoJiang-yw** [comment]
# Docker Network With Compose

## Introduction

Docker networks allow you to connect multiple containers together and have them communicate with each other, even across different hosts. In this challenge, you will learn how to set up and configure Docker networks in progressively more complicated scenarios.

## Prerequisites

- Before you begin this challenge, you should have basic knowledge of Docker and how to run containers using `docker run`.
- You should also have Docker installed on your machine.

## Step 1: Create a simple Docker network

### Introduction

In this step, you will create a simple Docker network with two containers connected to it. You will learn how to create a Docker network and how to connect containers to that network.

### Target

Create a Docker network named "my-network" and run two containers named "nginx-container" and "alpine-container" connected to that network.

### Requirements

You will need to have Docker installed on your machine.

### Result Example

Here is an example of what you should be able to accomplish at the end of this challenge:

- Create a Docker network named "my-network".
- Run an Nginx container named "nginx-container" connected to "my-network".
- Run an Alpine container named "alpine-container" connected to "my-network".
- Verify that the containers can communicate with each other by pinging one from the other.

## Step 2: Use a Docker network driver

### Introduction

In this step, you will learn how to use a Docker network driver. You will use a driver to create a network for your containers.

### Target

Use a Docker network driver to create a network for your containers.

### Requirements

You will need to have Docker installed on your machine.

### Result Example

Here is an example of what you should be able to accomplish at the end of this challenge:

- Use the bridge driver to create a network named "my-network2".
- Run a container named "alpine-container2" connected to "my-network2".
- Verify that the container can communicate with another container on the same network.

## Step 3: Use Docker networks with Compose

### Introduction

In this step, you will learn how to use Docker networks with Compose. You will create a simple Compose file that includes a network configuration.

### Target

Create a Compose file that includes a network configuration and run the containers using `docker-compose up`.

### Requirements

You will need to have Docker and Docker Compose installed on your machine.

### Result Example

Here is an example of what you should be able to accomplish at the end of this challenge:

- Create a Compose file that includes a network configuration.
- Run the containers using `docker-compose up`.
- Verify that the containers can communicate with each other by pinging one from the other.

**Comment by GuoJiang-yw** [comment]
# Solution

## Step 1: Create a simple Docker network

```
1. docker network create my-network
2. docker run -d --name nginx-container --network my-network nginx
3. docker run -itd --name alpine-container --network my-network alpine
4. docker exec -it alpine-container ping nginx-container
```

## Step 2: Use a Docker network driver

```
1. docker network create --driver bridge my-network2
2. docker run -itd --name alpine-container2 --network my-network2 alpine
3. docker run -d --name nginx-container2 --network my-network2 nginx
   docker exec -it alpine-container2 ping nginx-container2
```

## Step 3: Use Docker networks with Compose

1. Create a Compose file that includes a network configuration. For this example, we'll create a file named `docker-compose.yml`. Replace `nginx` with an image name you have access to:
   ```
   version: '3'
   services:
     nginx:
       image: nginx
       ports:
         - "80:80"
       networks:
         - my-network
     alpine:
       image: alpine
       command: ping nginx
       networks:
         - my-network
   networks:
     my-network:
   ```

2. Run the containers using `docker-compose up`:
   ```
   docker-compose up
   ```

3. The Compose file defines a container named `alpine` that pings the `nginx` container. Verify that the containers can communicate with each other.

**Comment by huhuhang** [comment]
@joker-bai 帮忙 Review 一下，合格的话取消 pending tag 和 Assignees

**Comment by joker-bai** [comment]
环境里没有docker-compose，要么加一个安装的步骤，要么减compose的步骤
