### ISSUE TITLE
lab-cancel-file-change

### ISSUE THREAD

**Issue by thenicebro** [labex-labs/scenarios#605]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Cancel File Change
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`linux/echo`**
- **`git/status`**
- **`git/restore`**
- **`git/rm`**
- **`git/status`**
- **`git/commit`**
- **`git/reset`**
- **`git/log`**

**Comment by thenicebro** [comment]
# Cancel File Change

## Introduction

In this lab, you will learn how to use three important Git commands: `restore`, `rm`, and `reset`. These commands are used to undo changes in your Git repository. Understanding how to use them is essential for effective version control.

# Undo the changes you made

The `git restore` command is used to discard changes in your working directory. This can be useful if you have made changes to a file that you no longer want to keep.

To use this command, you will first need to make changes to a file in your working directory. For example, you can add a line of text to a file:

```
$ echo "hello" > file.txt
```

Next, use the `git status` command to see the changes that you have made to the file:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)

      modified:   file.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

Finally, use the `git restore <filename>` command to discard the changes that you have made to the file:

```
$ git restore file.txt
```

The changes made to the file will be discarded and the file will be restored to its previous state.

# Remove a file from the repository

The `git rm` command is used to remove a file from your Git repository. This can be useful if you have added a file to your repository that you no longer want to keep.

First, use the `git status` command to see the files that have been modified or deleted:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

      modified:   another_file.txt
      deleted:    file.txt
```

Next, use the `git rm <filename>` command to remove the file from your Git repository:

```
$ git rm file.txt
```

Finally, use the `git commit -m "<commit message>"` command to commit the changes to your repository:

```
$ git commit -m "Removed file.txt"
```

The file will be removed from the Git repository and the changes will be committed.

# Undo and Reset

The `git reset` command is used to undo changes to your Git repository. This can be useful if you have made changes to your repository that you want to undo.

First, use the `git log` command to find the commit that you want to reset to:

```
$ git log
commit d1a2b3c4e5f6g7h8i9j0k1l2m3n4o5p6
Author: John Doe <johndoe@example.com>
Date:   Mon Apr 25 12:00:00 2023 -0400

    Added file.txt

commit a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
Author: John Doe <johndoe@example.com>
Date:   Mon Apr 24 12:00:00 2023 -0400

    Initial commit
```

In this example, we want to reset the repository to the initial commit with the hash `a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6`.

Next, use the `git reset --hard <commit>` command to reset the repository:

```
$ git reset --hard a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
```

This will reset the repository to the commit that you specified.

> Tips: You should fill in your hash value instead of this one on the example.

Finally, use the `git log` command again to confirm that your repository has been reset:

```
$ git log
commit a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
Author: John Doe <johndoe@example.com>
Date:   Mon Apr 24 12:00:00 2023 -0400

    Initial commit
```

The repository has been reset to the commit that you specified.

## Conclusion

In this lab, you learned how to use the `git restore`, `git rm`, and `git reset` commands. These commands are essential for effective version control and can help you undo changes that you have made to your Git repository. Remember to use these commands carefully and always make sure that you have a backup of your repository before making any changes.

**Comment by thenicebro** [comment]
需要在setup.sh里创建git工作目录`~/project/myrepo`, 并初始化为git仓库.

**Comment by huhuhang** [comment]
@thenicebro 你自己完成吧，后续我们尽量不创建 lab issue 了。
