### ISSUE TITLE
challenge-deploy-containerized-applications

### ISSUE THREAD

**Issue by GuoJiang-yw** [labex-labs/scenarios#623]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Deploy Containerized Applications
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`docker/build`**
- `docker/run`
- `docker/ps`
- `docker/images`

**Comment by GuoJiang-yw** [comment]
# Deploy Containerized Applications

## Introduction

In this challenge, you will learn the basics of Docker and how to use it to containerize and deploy a simple application. You will start with a simple "Hello, World!" application and containerize it, gradually adding more complexity to the container configuration.

## Step 1: Containerize a "Hello, World!" Application 

### Introduction

In this step, you will containerize a simple "Hello, World!" application using Docker. 

### Target

The target of this step is to create a Docker container that runs a "Hello, World!" application.

### Requirements

To complete this step, you will need to have Docker installed on your system.

### Result Example

1. Create a new directory called `docker-hello-world` in `/home/labex/project` path and navigate to this directory.

2. Create a file named `Dockerfile` in `/home/labex/project/docker-hello-world` path with the following content:

```bash
# Use busybox runtime as a parent image
# Run `echo "Hello, World!"` command
```

3. Use the `docker build` command to Build `hello-world` image.

4. When you run the Docker container with `hello-world` image, you should see the message "Hello, World!".

## Step 2: Containerize a Python Application

### Introduction

In this step, you will containerize a Python application using Docker.

### Target

The target of this step is to create a Docker container that runs a Python application.

### Requirements

To complete this step, you will need to have Docker installed on your system and a Python application that you want to containerize.

### Result Example

1. Create a new directory called `docker-python` in `/home/labex/project` path and navigate to this directory.

2. Create a file named `Dockerfile` in `/home/labex/project/docker-python` path with the following contents:

```bash
# Use python:3 as a parent image
# Set the working directory to /app
# Add the current directory contents into the container at /app
# Run the ["python", "app.py"] command to start the server
```

3. Create a file named `app.py` in your project directory `/home/labex/project/docker-python` with the following contents:

```python
print("Hello, Docker!")
```

4. Use the `docker build` command to Build `python-app` image.

5. When you run the Docker container with `python-app` image, you should see the output of the Python application.

## Step 3: Persist Data Using Docker Volumes

### Introduction

In this step, you will learn how to use Docker volumes to persist data.

### Target

The target of this step is to create a Docker container that uses a volume to persist data.

### Requirements

To complete this step, you will need to have Docker installed on your system and a Python application that writes data to a file.

### Result Example

1. Create a new directory called `docker-volume` in `/home/labex/project` path and navigate to this directory.

2. Create a file named `Dockerfile` in `/home/labex/project` path with the following contents:

```bash
# Use python:3 as a parent image
# Set the working directory to /app
# Add the current directory contents into the container at /app
# creates a mount point at /data
# Run the ["python", "app.py"] command to start the server
```

3. Create a file named `app.py` in your project directory `/home/labex/project/docker-volum` with the following contents:

```python
print("Hello, Docker-volume!")
```

4. Use the `docker build` command to Build `python-volume` image.

5. Run the Docker container with `python-volume` image, use `-v` mount to the host `$(pwd)/data` path. Use `-it` to interact with the container. Inside the container, write data to the mounted volume. Finally, use `CTRL+p+q` to make the container run.

6. Validate the Docker volume to persist the data. In the current directory of host, there is a `data` directory with a `hello.txt` file.

**Comment by GuoJiang-yw** [comment]
# Solution

## Step 1: Containerize a "Hello, World!" Application 

```bash
1. mkdir docker-hello-world
   cd docker-hello-world

2. FROM busybox
   CMD echo "Hello, World!"

3. docker build -t hello-world .

4. docker run hello-world
```

## Step 2: Containerize a Python Application

```bash
1. mkdir docker-python
   cd docker-python

2. FROM python:3
   WORKDIR /app
   ADD . /app
   CMD ["python", "app.py"]

3. print("Hello, Docker!")

4. docker build -t python-app .

5. docker run python-app
```

## Step 3: Persist Data Using Docker Volumes

```bash
1.  mkdir docker-volume
    cd docker-volume

2. FROM python:3
   WORKDIR /app
   ADD . /app
   VOLUME /data
   CMD ["python", "app.py"]

3. print("Hello, Docker-volume!")

4. docker build -t python-volume .

5. docker run -it -v $(pwd)/data:/data python-volume bash
   Inside the container input:
   echo "Hello, World!" > /data/hello.txt

6. cat $(pwd)/data/hello.txt
```

**Comment by GuoJiang-yw** [comment]
# Verify Script

## Step 1: Containerize a "Hello, World!" Application 

```bash
1. test -d "/home/labex/project/docker-hello-world"
2. test -f "/home/labex/project/docker-hello-world/Dockerfile"
3. docker images | grep hello-world
4. docker ps -a | grep hello-world
```

## Step 2: Containerize a Python Application

```bash
1. test -d "/home/labex/project/docker-python"
2. test -f "/home/labex/project/docker-python/Dockerfile"
3. test -f "/home/labex/project/docker-python/app.py"
4. docker images | grep python-app
5. docker ps -a | grep python-app
```

## Step 3: Persist Data Using Docker Volumes

```bash
1. test -d "/home/labex/project/docker-volume"
2. test -f "/home/labex/project/docker-volume/Dockerfile"
3. test -f "/home/labex/project/docker-volume/app.py"
4. docker images | grep python-volume
5. docker ps | grep python-volume
6. test -f "/home/labex/project/docker-volume/data/hello.txt
```

**Comment by huhuhang** [comment]
> > **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**
> 
> ## Basic
> > Basic information about the scenario, which can be changed if required.
> > 实验/挑战的基本信息，如有需要，可以修改。
> 
> * **Suggest Title 建议标题**: Deploy Containerized Applications
> * **Suggest Steps 建议步骤数**: 3
> * **Suggest Image 建议环境**: `webide-ubuntu:2204`
> 
> ## Sources
> > Issues has provided the material; the part not provided must be completed by the author.
> > Issues 已经提供了材料；没有提供的部分由作者自行补充完成。
> 
> * [x]  Full Text 正文内容
> * [x]  Reference Answers 参考答案
> * [x]  Verify Script 检测脚本
> 
> ## Skills
> > Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> > 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)
> 
> * **`docker/build`**
> * `docker/run`
> * `docker/ps`
> * `docker/images`

docker 的内容应该需要带 instance 的环境才行吧。

**Comment by huhuhang** [comment]
@GuoJiang-yw 直接分配给你了。
