### ISSUE TITLE
challenge-docker-create-command

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#655]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Docker Create Command
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`docker/create`**
- `docker/inspect`

**Comment by joker-bai** [comment]
# Docker Create Command

## Introduction

Docker is a popular platform for developing, shipping, and running applications. The `docker create` command is used to create a new container from an image. In this challenge, you will learn how to use the `docker create` command to create a new container step-by-step.

## Step 1: Create a Container from an Image

### Introduction

In this step, you will learn how to create a new container from an image using the `docker create` command.

### Target

Create a new container from the `nginx` image.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Open a terminal or command prompt.
2. Create a new container from the `nginx` image.

### Solution

1. Open a terminal or command prompt.
2. Run the following command:

```bash
docker create nginx
```

### Requirements

- Docker must be installed on your machine.

## Step 2: Name the Container

### Introduction

In this step, you will learn how to name a container using the `--name` option.

### Target

Name the container `my-nginx`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Open a terminal or command prompt.
2. Create a new container called `my-nginx` from the `nginx` image.
3. Check if the container has been created.

### Solution

1. Open a terminal or command prompt.
2. Run the following command:

```bash
docker create --name my-nginx nginx
```

3. Check if the container has been created.

```bash
docker ps -a | grep my-nginx
```

### Requirements

- Docker must be installed on your machine.

## Step 3: Map Ports

### Introduction

In this step, you will learn how to map ports using the `-p` option.

### Target

Map port `8080` on the host to port `80` in the container.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Open a terminal or command prompt.
2. Create a new container called `my-nginx2` from the `nginx` image and map port `8080` on the host to port `80` in the container.
3. Check if the host port mapping is in the container configuration.

### Solution

1. Open a terminal or command prompt.
2. Run the following command:

```bash
docker create --name my-nginx2 -p 8080:80 nginx
```

3. Check if the host port mapping is in the container configuration.

```bash
docker inspect my-nginx2 | grep HostPort
```

### Requirements

- Docker must be installed on your machine.

## Step 4: Set Environment Variables

### Introduction

In this step, you will learn how to set environment variables using the `-e` option.

### Target

Set the `NGINX_HOST` environment variable to `example.com`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Open a terminal or command prompt.
2. Create a new container called `my-nginx3` from the `nginx` image and set the `NGINX_HOST` environment variable to `example.com` in the container.
3. Check if the environment variable is in the container configuration.

### Solution

1. Open a terminal or command prompt.
2. Run the following command:

```bash
docker create --name my-nginx3 -e NGINX_HOST=example.com nginx
```

3. Check if the environment variable is in the container configuration.

```bash
docker inspect my-nginx3 | grep NGINX_HOST
```

### Requirements

- Docker must be installed on your machine.

## Step 5: Mount Volumes

### Introduction

In this step, you will learn how to mount volumes using the `-v` option.

### Target

Mount the `/var/www` directory on the host to the `/usr/share/nginx/html` directory in the container.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Open a terminal or command prompt.
2. Create a new container called `my-nginx4` from the `nginx` image and mount the `/var/www` directory on the host to the `/usr/share/nginx/html` directory in the container.
3. Check if the volume mount of the container is configured in the container.

### Solution

1. Open a terminal or command prompt.
2. Run the following command:

```bash
docker create --name my-nginx4 -v /var/www:/usr/share/nginx/html nginx
```

3. Check if the volume mount of the container is configured in the container.

```bash
docker inspect my-nginx4 | grep "/var/www"
```

### Requirements

- Docker must be installed on your machine.

## Summary

In this challenge, you learned how to use the `docker create` command to create a new container step-by-step. You learned how to create a container from an image, name the container, map ports, set environment variables, and mount volumes. With these skills, you can create and configure containers to run your applications in Docker.

**Comment by joker-bai** [comment]
具体要求：
1、按照官方要求根据内容进行拆分，注意markdown的语法和官方要求的格式。
2、每个`Result Example`的步骤需要给出具体的结果截图。
3、如果觉得部分内容的描述或者写法不是很合理，可以自行修改内容，也可以找我来修改issue的内容。

**Comment by anonym10048** [comment]
2023/5/6 anonym10048
